export const DEFAULT_MEMBER = (isHoF = false) => ({
  isHoF,
  isChild: isHoF ? false : (null as boolean | null),
  relationWithHeadOfFamily: "",
  memberName: "",
  aadhaarNo: "",
  mobileNo: "",
  dateOfBirth: "",
  gender: "",
  digitalRationCardNo: "",
  digitalRationCardType: "",
  hasDigitalRationCard: null as boolean | null,
  liftingMonthlyRation: null as boolean | null,
  socialCategory: "",
  bankAccountNo: "",
  ifscCode: "",
  bankName: "",
  epicNo: "",
  assemblyConstituencyNo: "",
  partNo: "",
  caaApplicationStatus: "Not Applicable",
  caaApplicationNo: "",
  caaCertificateNo: "",
  otherSpecificIds: [] as { idType: string, idNumber: string, issueDate: string, issuingAuthority: string }[],
  sir2026TribunalStatus: "Not Applicable",
  sir2026CaseDetails: "",
  hasThreePuccaRooms: null as boolean | null,
  ownsLand: null as boolean | null,
  landholdingSizeDecimals: null as number | null,
  hasFourWheeler: false,
  vehicleCount: null as number | null,
  vehicleRegistrationNo: "",
  vehicleModel: "",
  hasHealthInsurance: false,
  healthInsuranceType: "",
  healthInsuranceSumAssured: null as number | null,
  healthInsuranceAnnualPremium: null as number | null,
  literacyStatus: "",
  highestEducationalQualifications: "",
  natureOfEmployment: [] as string[],
  paysIncomeOrProfessionalTax: null as boolean | null,
  hasPanCard: null as boolean | null,
  panName: "",
  panNo: "",
  holdsConstitutionalPost: null as boolean | null,
  constitutionalPostMemberNo: "",
  isGovtPensioner: null as boolean | null,
  govtPensionerMemberNo: "",
  isRegisteredGst: null as boolean | null,
  gstin: "",
  disabilityIdNo: "",
  disabilityIssuedDate: "",
  disabilityPercentage: null as number | null,
  disabilityIssuingAuthority: "",
  otherIdNo: "",
  otherIdIssuedDate: "",
  otherIdIssuingAuthority: "",
  schoolName: "",
  schoolGrade: "",
  schoolType: "",
  schoolTypeOther: "",
  vaccinationStatus: "",
  vaccinationCardId: "",
  vaccinationSkipReasonOrDate: "",
  receivesGovtSchemeBenefits: false,
  govtSchemeBenefits: [JSON.stringify({ schemeName: "", optOut: false })],
  applyingForAnnapurnaBhandar: null as boolean | null
});

export const SECTIONS = [
  { key: "basic", label: "Basic Info", icon: "person" },
  { key: "ration", label: "Ration Card / Food Subsidy", icon: "shopping_cart" },
  { key: "assets", label: "Assets", icon: "home" },
  { key: "income", label: "Income / Profession", icon: "payments" },
  { key: "identity", label: "Identity Docs", icon: "badge" },
  { key: "schemes", label: "Govt Schemes", icon: "account_balance" },
];

export const DOC_KEY_MAPPING: Record<string, number> = {
  "aadhaar": 101,
  "epic": 102,
  "pan": 103,
  "bankAccount": 104,
  "digitalRationCard": 105,
  "casteCertificate": 106,
  "healthInsurance": 107,
  "landDocuments": 108,
  "vaccinationCard": 109,
  "sirApplication": 110,
  "caaApplication": 111,
  "employmentDocument": 112,
  "pensionDocument": 113,
};

export function getDocLimits(key: string, documentMasterData: any[] | null) {
  if (!documentMasterData || !Array.isArray(documentMasterData)) return {};
  let docTypeId = DOC_KEY_MAPPING[key];
  if (key.startsWith('otherSpecificId_')) docTypeId = 114;
  const doc = documentMasterData.find((d: any) => d.doc_type_id === docTypeId);
  return doc ? { minSizeKB: doc.minSize, maxSizeKB: doc.maxSize } : {};
}
